# Building Cactus on Gitlab is slow and often crashes with errors like:
# E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-9.1ubuntu1_amd64.deb  Undetermined Error [IP: 91.189.88.142 80]
# E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
# So we try to avoid that by keeping a base image around with dependencies pre-installed that CI can use.

FROM quay.io/vgteam/dind

# apt dependencies for build
RUN apt-get update && apt-get install -y build-essential git python3 python3-dev python3-pip zlib1g-dev wget libbz2-dev pkg-config libhdf5-dev liblzo2-dev libtokyocabinet-dev

