#!/bin/bash
# Download and statically build tools needed for cactus-refmap and cactus-graphmap.  They are
# - minimap2
# - minigraph
# - gfatools
# - mzgaf2paf
# - paf2lastz
# If, updating any versions here, update the release notes as well
#
# all binaries get copied into cactus/bin

set -beEu -o pipefail

miniBuildDir=$(realpath -m build-mini)
binDir=$(pwd)/bin
CWD=$(pwd)

set -x
rm -rf ${miniBuildDir}
mkdir -p ${miniBuildDir}
mkdir -p ${binDir}

# minimap2
cd ${miniBuildDir}
git clone https://github.com/lh3/minimap2.git
cd minimap2
git checkout c9874e2dc50e32bbff4ded01cf5ec0e9be0a53dd
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd minimap2 | grep so | wc -l) -eq 0 ]
then
	 mv minimap2 ${binDir}
else
	 exit 1
fi

# minigraph
cd ${miniBuildDir}
git clone https://github.com/lh3/minigraph.git
pushd minigraph
git checkout 78ce999c96756b677567e3069a5c6fc3962500fb
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd minigraph | grep so | wc -l) -eq 0 ]
then
	 mv minigraph ${binDir}
else
	 exit 1
fi

# gfatools
cd ${miniBuildDir}
git clone https://github.com/lh3/gfatools.git
cd gfatools
git checkout a1abaf3d6d4510bc73e5defab274cfb288a11255
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd gfatools | grep so | wc -l) -eq 0 ]
then
	 mv gfatools ${binDir}
else
	 exit 1
fi

# mzgaf2paf
cd ${miniBuildDir}
git clone https://github.com/glennhickey/mzgaf2paf.git
cd mzgaf2paf
git checkout 57fe57f9a5101ddf15da5b42b9ab3dcaf147af62
CXXFLAGS="-static" make -j 4
if [ $(ldd mzgaf2paf | grep so | wc -l) -eq 0 ]
then
	 mv mzgaf2paf ${binDir}
else
	 exit 1
fi

# paf2lastz
wget https://github.com/glennhickey/paf2lastz/releases/download/v1.1/paf2lastz
chmod +x paf2lastz
if [ $(ldd paf2lastz | grep so | wc -l) -eq 0 ]
then
	 mv paf2lastz ${binDir}
else
	 exit 1
fi 

cd ${CWD}
rm -rf ${miniBuildDir}
