#!/bin/bash
# Download and statically build tools needed for cactus-refmap and cactus-graphmap.  They are
# - minimap2
# - minigraph
# - gfatools
# - mzgaf2paf
# - paf2lastz
# If, updating any versions here, update the release notes as well
#
# all binaries get copied into cactus/bin

set -beEu -o pipefail

miniBuildDir=$(realpath -m build-mini)
binDir=$(pwd)/bin
# just use cactusRootPath for now
dataDir=$(pwd)/src/cactus
CWD=$(pwd)

set -x
rm -rf ${miniBuildDir}
mkdir -p ${miniBuildDir}
mkdir -p ${binDir}

# minimap2
cd ${miniBuildDir}
git clone https://github.com/lh3/minimap2.git
cd minimap2
git checkout c9874e2dc50e32bbff4ded01cf5ec0e9be0a53dd
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd minimap2 | grep so | wc -l) -eq 0 ]
then
	 mv minimap2 ${binDir}
else
	 exit 1
fi

# minigraph
cd ${miniBuildDir}
git clone https://github.com/lh3/minigraph.git
pushd minigraph
git checkout 78ce999c96756b677567e3069a5c6fc3962500fb
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd minigraph | grep so | wc -l) -eq 0 ]
then
	 mv minigraph ${binDir}
else
	 exit 1
fi

# gfatools
cd ${miniBuildDir}
git clone https://github.com/lh3/gfatools.git
cd gfatools
git checkout a1abaf3d6d4510bc73e5defab274cfb288a11255
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/'
CFLAGS="-static" make -j 4
if [ $(ldd gfatools | grep so | wc -l) -eq 0 ]
then
	 mv gfatools ${binDir}
else
	 exit 1
fi

# dna-brnn
cd ${miniBuildDir}
git clone https://github.com/lh3/dna-nn.git
cd dna-nn
git checkout 2e6d242ae339457b985f50086e85194c3ce418b1
# hack in a static build
sed -i Makefile -e 's/CFLAGS=/CFLAGS+=/' -e 's/LIBS=/LIBS+=/'
CFLAGS="-static" LIBS="-static" make -j 4
if [ $(ldd dna-brnn | grep so | wc -l) -eq 0 ]
then
	 mv dna-brnn ${binDir}
	 cp models/attcc-alpha.knm ${dataDir}
else
	 exit 1
fi

# mzgaf2paf
cd ${miniBuildDir}
git clone https://github.com/glennhickey/mzgaf2paf.git
cd mzgaf2paf
git checkout c43c0b6121b95979ff484106a6c543180cdd89a2
CXXFLAGS="-static" make -j 4
if [ $(ldd mzgaf2paf | grep so | wc -l) -eq 0 ]
then
	 mv mzgaf2paf ${binDir}
else
	 exit 1
fi

# paf2lastz
wget https://github.com/glennhickey/paf2lastz/releases/download/v1.1/paf2lastz
chmod +x paf2lastz
if [ $(ldd paf2lastz | grep so | wc -l) -eq 0 ]
then
	 mv paf2lastz ${binDir}
else
	 exit 1
fi 

cd ${CWD}
rm -rf ${miniBuildDir}

echo "--------------------------------------------------"
echo "(re)run pip install -U . to install dna-brnn model"
echo "--------------------------------------------------"
