rootPath = ../
include ../include.mk

all: ${binPath}/cactus_coveredSeeds ${binPath}/cactus_adjustSamplingRates

${binPath}/cactus_coveredSeeds:
	mv cactus_coveredSeeds.py ../bin/cactus_coveredSeeds
	chmod +x ../bin/cactus_coveredSeeds

${binPath}/cactus_adjustSamplingRates:
	mv cactus_adjustSamplingRates.py ../bin/cactus_adjustSamplingRates
	chmod +x ../bin/cactus_adjustSamplingRates
