rootPath = ../
include ../include.mk
sources = maftocigar.c
CFLAGS = --std=c99 -g -Wall
all:
	#gcc -o maftocigar maftocigar.c
	#cp maftocigar ${binPath}
	cp maftocigarpy ${binPath}/maftocigar
	
clean:
	cd ${binPath} && rm maftocigar
	
