#!/usr/bin/env bash

# Script to make paf alignment file input to cactus from paf format alignments

# print arguments if no input files given
if [[ $# -eq 0 ]]; then
    echo "cactus_chain [alignment_files.paf]xN"
    exit 2
fi

# exit when any command fails
set -e

# log the commands its running
set -x

# Temporary chain files
temp_dir=$(mktemp -d -t temp_chains-XXXXXXXXXX)
# Make sure we cleanup the temp dir
trap 'rm -rf ${temp_dir}' EXIT
pair_chains=${temp_dir}/pair_chains.paf
chains=${temp_dir}/chains.paf

# Make chains
for align_file in "$@"
do
  paf_chain -i "$align_file" > "$pair_chains"
  cat "$pair_chains" >> "$chains"
  paf_invert -i "$pair_chains" >> "$chains"
done

# Make the tiled chains and pipe to stdout
paf_tile -i "$chains"