#!/usr/bin/env python3

"""
Unit tests for the plan post-processing in cactus-update-prepare: the code that turns a plan
printed by cactus-prepare into an update plan, by dropping the cactus-preprocess jobs of
genomes that are already aligned, adding --includeRoot to the last round, and removing the
HAL merging section and the root's hal2fasta job.

These are fast and offline.  Nothing is aligned: the canned plans below are fed straight to
make_plan(), and the one test that does call cactus-prepare only makes it print a plan.  The
end-to-end update is covered by evolverTest.py's testEvolverUpdateNodeLocal and
testEvolverUpdateBranchLocal.
"""

import os
import re
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from cactus.update import cactus_update_prepare as cup

# A plan for adding a genome within a branch: two rounds, and a HAL merging section holding
# one cactus-halAppendSubtrees line per batch of genomes plus the "rm -f" cleaning up the
# intermediate HAL.  Printed by cactus-prepare, only the paths shortened.
BRANCH_PLAN = """\
## generated by : cactus-prepare seq_file.in --outDir out --outSeqFile out/seq.txt --outHal out/final.hal --jobStore js --halAppendBatchSize 1
## date : 2026-09-09 09:15:08.077617
## cactus commit : 1f64bf9206bb6ca6a83d3118cb3c52d7140a2960


## Preprocessor
cactus-preprocess js/0 seq_file.in out/seq.txt --inputNames simMouse simRat simHuman simGorilla   2>&1 | tee out/logs/preprocess-simMouse.log

## Alignment
### Round 0
cactus-blast js/1 out/seq.txt out/AncGorilla.paf.gz --root AncGorilla   2>&1 | tee out/logs/blast-AncGorilla.log
cactus-align js/2 out/seq.txt out/AncGorilla.paf.gz out/AncGorilla.hal --root AncGorilla   2>&1 | tee out/logs/align-AncGorilla.log
cactus-hal2fasta js/3 out/AncGorilla.hal AncGorilla out/AncGorilla.fa.gz   2>&1 | tee out/logs/hal2fasta-AncGorilla.log

cactus-blast js/4 out/seq.txt out/mr.paf.gz --root mr   2>&1 | tee out/logs/blast-mr.log
cactus-align js/5 out/seq.txt out/mr.paf.gz out/mr.hal --root mr   2>&1 | tee out/logs/align-mr.log
cactus-hal2fasta js/6 out/mr.hal mr out/mr.fa.gz   2>&1 | tee out/logs/hal2fasta-mr.log

### Round 1
cactus-blast js/7 out/seq.txt out/Anc1.paf.gz --root Anc1   2>&1 | tee out/logs/blast-Anc1.log
cactus-align js/8 out/seq.txt out/Anc1.paf.gz out/Anc1.hal --root Anc1   2>&1 | tee out/logs/align-Anc1.log
cactus-hal2fasta js/9 out/Anc1.hal Anc1 out/Anc1.fa.gz   2>&1 | tee out/logs/hal2fasta-Anc1.log

## HAL merging
cactus-halAppendSubtrees js/10 out/Anc1.hal out/AncGorilla.hal out/Anc1.hal.append.0   2>&1 | tee out/logs/halAppend-AncGorilla.log
cactus-halAppendSubtrees js/11 out/Anc1.hal.append.0 out/mr.hal out/final.hal   2>&1 | tee out/logs/halAppend-mr.log
rm -f out/Anc1.hal.append.0
"""

# A plan for adding a genome to an existing node: a single round, and a HAL merging section
# that is only a heading, there being no other genome to append.  This is the common case.
NODE_PLAN = """\
## generated by : cactus-prepare seq_file.in --outDir out --outSeqFile out/seq.txt --outHal out/final.hal --jobStore js
## date : 2026-09-09 09:14:03.560665
## cactus commit : 1f64bf9206bb6ca6a83d3118cb3c52d7140a2960


## Preprocessor
cactus-preprocess js/0 seq_file.in out/seq.txt --inputNames simMouse simRat simGorilla   2>&1 | tee out/logs/preprocess-simMouse.log

## Alignment
### Round 0
cactus-blast js/1 out/seq.txt out/mr.paf.gz --root mr   2>&1 | tee out/logs/blast-mr.log
cactus-align js/2 out/seq.txt out/mr.paf.gz out/final.hal --root mr   2>&1 | tee out/logs/align-mr.log
cactus-hal2fasta js/3 out/final.hal mr out/mr.fa.gz   2>&1 | tee out/logs/hal2fasta-mr.log

## HAL merging
"""

# cactus-prepare only appends "2>&1 | tee <log>" when it was given an --outDir to put logs in
NO_REDIRECT = re.compile(r"\s+2>&1 \| tee \S+")


def update_plan(plan, preprocess_to_remove=()):
    """Runs make_plan over an already-printed cactus-prepare plan

    Everything make_plan does before the post-processing needs a seqFile on disk and a
    cactus-prepare call, so it is stubbed out: the plan is the input under test here.
    """
    with patch.object(cup, "create_seq_file"), \
         patch.object(cup, "call_cactus_prepare", return_value=plan), \
         patch.object(cup, "get_generation_info", return_value="## generated by : test\n"):
        return cup.make_plan(
            "seq_file.in", "out", "js", "out/seq.txt", "",
            "(simGorilla:0.075)AncGorilla;", {}, list(preprocess_to_remove),
        )


def command_lines(plan):
    """The command lines of a plan, dropping headings and blank lines"""
    return [line for line in plan.split("\n") if line.strip() and not line.lstrip().startswith("#")]


class TestPreprocessJobs(unittest.TestCase):
    """--inputNames holds genome names that must reach cactus-preprocess unharmed"""

    def preprocess_line(self, plan):
        lines = [line for line in plan.split("\n") if "cactus-preprocess" in line]
        self.assertEqual(len(lines), 1, "expected exactly one cactus-preprocess job")
        return lines[0]

    def test_names_kept_when_nothing_is_removed(self):
        line = self.preprocess_line(update_plan(BRANCH_PLAN))
        self.assertIn("--inputNames simMouse simRat simHuman simGorilla ", line)

    def test_names_keep_their_order_and_spelling_when_some_are_removed(self):
        line = self.preprocess_line(update_plan(BRANCH_PLAN, ["simMouse", "simHuman"]))
        self.assertIn("--inputNames simRat simGorilla ", line)

    def test_redirection_survives_the_edit(self):
        # the names are not the end of the line: the shell suffix must be left alone
        line = self.preprocess_line(update_plan(BRANCH_PLAN, ["simMouse"]))
        self.assertTrue(line.endswith("2>&1 | tee out/logs/preprocess-simMouse.log"), line)

    def test_names_are_kept_whole_without_a_redirection(self):
        # with no suffix the names end the line, which is where a trailing-character strip
        # would eat into the last one ("simRat" -> "simR")
        line = self.preprocess_line(update_plan(NO_REDIRECT.sub("", BRANCH_PLAN)))
        self.assertTrue(line.endswith("--inputNames simMouse simRat simHuman simGorilla"), line)

    def test_job_is_dropped_once_no_name_is_left(self):
        plan = update_plan(BRANCH_PLAN, ["simMouse", "simRat", "simHuman", "simGorilla"])
        self.assertNotIn("cactus-preprocess", plan)


class TestIncludeRoot(unittest.TestCase):
    """--includeRoot is for the last round only, and belongs to cactus, not to tee"""

    def test_added_to_the_last_round_before_the_redirection(self):
        plan = update_plan(BRANCH_PLAN)
        self.assertIn("--root Anc1   --includeRoot 2>&1 | tee out/logs/blast-Anc1.log", plan)
        self.assertIn("--root Anc1   --includeRoot 2>&1 | tee out/logs/align-Anc1.log", plan)

    def test_added_to_the_blast_and_align_of_the_last_round_only(self):
        plan = update_plan(BRANCH_PLAN)
        self.assertEqual(plan.count("--includeRoot"), 2)
        for line in plan.split("\n"):
            if "--includeRoot" in line:
                self.assertIn("Anc1", line, "--includeRoot reached an earlier round")

    def test_appended_at_the_end_without_a_redirection(self):
        plan = update_plan(NO_REDIRECT.sub("", BRANCH_PLAN))
        self.assertEqual(plan.count("--includeRoot"), 2)
        for line in plan.split("\n"):
            if "--includeRoot" in line:
                self.assertTrue(line.endswith(" --includeRoot"), line)


class TestHalMerging(unittest.TestCase):
    """An update amends the HAL it was given; it never stitches a new one together"""

    def test_whole_section_is_removed(self):
        plan = update_plan(BRANCH_PLAN)
        self.assertNotIn("## HAL merging", plan)
        self.assertNotIn("halAppendSubtrees", plan)
        self.assertNotIn("rm -f", plan)

    def test_heading_only_section_is_removed(self):
        self.assertNotIn("HAL merging", update_plan(NODE_PLAN))

    def test_root_hal2fasta_is_dropped_and_the_others_kept(self):
        plan = update_plan(BRANCH_PLAN)
        self.assertNotIn("hal2fasta-Anc1.log", plan)
        self.assertIn("hal2fasta-AncGorilla.log", plan)
        self.assertIn("hal2fasta-mr.log", plan)


class TestPlanIntegrity(unittest.TestCase):
    """The post-processing edits command lines; it must not rewrite them

    Command lines carry shell metacharacters, so any of them used as a regex, or as a
    replacement, garbles the plan.
    """

    def test_no_command_line_is_invented_or_mangled(self):
        # nothing is removed from --inputNames here, so --includeRoot is the only edit
        # the post-processing is allowed to make to any command line
        original = set(BRANCH_PLAN.split("\n"))
        for line in command_lines(update_plan(BRANCH_PLAN)):
            self.assertIn(line.replace(" --includeRoot", ""), original,
                          "post-processing rewrote a command line: %r" % line)

    def test_no_command_line_is_duplicated(self):
        lines = command_lines(update_plan(BRANCH_PLAN))
        self.assertEqual(len(lines), len(set(lines)))

    def test_amendments_start_on_a_blank_line(self):
        for name, plan in (("branch", BRANCH_PLAN), ("node", NODE_PLAN)):
            amended = cup.make_plan_amendments(
                update_plan(plan), ["halReplaceGenome in.hal mr"], ["halValidate in.hal"])
            lines = amended.split("\n")
            self.assertEqual(lines[lines.index("## Alignment update") - 1], "",
                             "%s plan: no blank line before the amendments" % name)


class TestCactusPrepareFormat(unittest.TestCase):
    """The post-processing keys off the exact shape of a cactus-prepare plan

    Run the real cactus-prepare, which only prints a plan, so that a change to that shape is
    caught here instead of silently disabling the post-processing.  That is how update plans
    came to keep their merging commands: the pattern removing them had been written for a
    "cactus-halAppendSubtree" that had since gained a plural.
    """

    def prepare_plan(self, tree, genomes):
        tmp = tempfile.mkdtemp()
        seq_file = os.path.join(tmp, "seq_file.in")
        with open(seq_file, "w") as f:
            f.write("%s\n\n" % tree)
            for genome in genomes:
                fasta = os.path.join(tmp, "%s.fa" % genome)
                with open(fasta, "w") as g:
                    g.write(">chr1\nACGTACGTACGTACGTACGT\n")
                f.write("%s %s\n" % (genome, fasta))

        return subprocess.check_output(
            [sys.executable, "-m", "cactus.progressive.cactus_prepare", seq_file,
             "--outDir", os.path.join(tmp, "out"),
             "--outSeqFile", os.path.join(tmp, "out", "seq.txt"),
             "--outHal", os.path.join(tmp, "out", "final.hal"),
             "--jobStore", os.path.join(tmp, "js"),
             # one genome appended per command, so that the intermediate HAL and the "rm -f"
             # cleaning it up both show up
             "--halAppendBatchSize", "1"],
            universal_newlines=True)

    def test_a_real_plan_still_looks_like_the_canned_ones(self):
        plan = self.prepare_plan(
            "((simMouse:0.08,simRat:0.09)mr:0.27,(simHuman:0.04,simGorilla:0.075)AncGorilla:0.1)Anc1;",
            ["simMouse", "simRat", "simHuman", "simGorilla"])

        # the pieces the post-processing looks for
        self.assertIn("## Preprocessor", plan)
        self.assertIn("--inputNames", plan)
        self.assertIn("## Alignment", plan)
        self.assertIn("## HAL merging", plan)
        self.assertRegex(plan, r"(?m)^cactus-blast ")
        self.assertRegex(plan, r"(?m)^cactus-align ")
        self.assertRegex(plan, r"(?m)^cactus-hal2fasta ")
        self.assertRegex(plan, r"(?m)^rm -f ")
        # the shell suffix that must not be mistaken for part of a cactus command
        self.assertIn("2>&1 | tee ", plan)
        # the merging commands, whose exact spelling the removal depends on
        self.assertRegex(plan, r"(?m)^cactus-halAppendSubtrees ")

    def test_a_real_plan_is_post_processed(self):
        plan = self.prepare_plan(
            "((simMouse:0.08,simRat:0.09)mr:0.27,(simHuman:0.04,simGorilla:0.075)AncGorilla:0.1)Anc1;",
            ["simMouse", "simRat", "simHuman", "simGorilla"])
        updated = update_plan(plan, ["simMouse", "simRat"])

        self.assertNotIn("HAL merging", updated)
        self.assertNotIn("halAppendSubtrees", updated)
        self.assertNotIn("rm -f", updated)
        self.assertIn("--inputNames simHuman simGorilla ", updated)
        self.assertRegex(updated, r"--includeRoot 2>&1 \| tee \S+blast-Anc1\.log")
        self.assertRegex(updated, r"--includeRoot 2>&1 \| tee \S+align-Anc1\.log")


if __name__ == "__main__":
    unittest.main()
